"""fix like model field name

Revision ID: 368c74b0627e
Revises: 4c31c76c71a6
Create Date: 2023-05-30 21:36:44.431105

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '368c74b0627e'
down_revision = '4c31c76c71a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('like_parent_id_fkey', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'post', ['post_id'], ['id'])
    op.drop_column('like', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_parent_id_fkey', 'like', 'post', ['parent_id'], ['id'])
    op.drop_column('like', 'post_id')
    # ### end Alembic commands ###
