"""post model fix

Revision ID: 40aabc6bb8b7
Revises: 36c0e24b5d3d
Create Date: 2023-05-22 22:22:43.901360

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '40aabc6bb8b7'
down_revision = '36c0e24b5d3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
