"""initial

Revision ID: ac974b21d50d
Revises: 
Create Date: 2023-05-16 21:47:58.984776

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'ac974b21d50d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
